-- Remove the unused blog_drafts review pipeline.
-- The daily blog post is generated by a Claude Code remote trigger that
-- writes .mdx files directly to a branch, so the drafts table is obsolete.

drop table if exists public.blog_drafts;
